Autoshop.Web/Controllers/AppointmentsController.cs
namespace Autoshop.Web.Controllers
{
    using Autoshop.Models;
    using Autoshop.Services;
    using Autoshop.Services.Implementations;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models.AppointmentsViewModels;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class AppointmentsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IAppointmetsService appointments;
        private readonly ISpecialsService specials;

        public AppointmentsController(UserManager<User> userManager, IAppointmetsService appointments, ISpecialsService specials)
        {
            this.userManager = userManager;
            this.appointments = appointments;
            this.specials = specials;
        }

        public async Task<IActionResult> Index(int? specialId = null)
        {
            var model = new AppointmentViewModel();
            var specialToShowId = specialId != null ? specialId.Value : 0;
            if (specialToShowId > 0)
            {
                var special = await this.specials.Find(specialToShowId);
                if (special != null)
                {
                    model.SpecialId = special.Id;
                    model.Special = special;
                }
            }

            if (User.Identity.IsAuthenticated)
            {
                var user = await userManager.GetUserAsync(User);

                model.FirstName = user.FirstName;
                model.LastName = user.LastName;
                model.Email = user.Email;
                model.PhoneNumber = user.PhoneNumber;
            }

            model.Specials = await this.PopulateSpeciaslOptions(specialToShowId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(AppointmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (User.Identity.IsAuthenticated)
            {
                var userId = this.userManager.GetUserId(User);
                model.UserId = userId;
            }

            await this.appointments.Add(model.FirstName, model.LastName, model.Email, model.PhoneNumber, model.VehicleInformation, model.Reason, model.DateTime, model.SpecialId, model.UserId);

            return RedirectToAction(nameof(Success));
        }

        public IActionResult Success()
        {
            return View();
        }
        
        private async Task<List<SelectListItem>> PopulateSpeciaslOptions(int specialId)
        {
            var allSpecials = await this.specials.All(true);

            return allSpecials.Select(s => new SelectListItem
            {
                Text = s.Title,
                Value = s.Id.ToString(),
                Selected = s.Id == specialId
            })
            .ToList();
        }
    }
}

Autoshop.Web/Controllers/BlogController.cs
namespace Autoshop.Web.Controllers
{
    using Autoshop.Services;
    using Autoshop.Web.Models;
    using Autoshop.Web.Models.BlogViewModels;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Authorization;
    using Autoshop.Models;
    using Microsoft.AspNetCore.Identity;
    using Autoshop.Web.Infrastructure.Extensions;
    using System;
    
    using static Autoshop.Common.Constants.CommonConstants;

    public class BlogController : Controller
    {
        private readonly IBlogService blog;
        private readonly UserManager<User> userManager;

        public BlogController(IBlogService blog, UserManager<User> userManager)
        {
            this.blog = blog;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Articles(int page = 1, string categoryName = "")
        {
            var posts = await this.blog.All(page, PostsPerPage, categoryName);
            var categories = await this.blog.Categories();

            foreach (var post in posts)
            {
                post.Text = post.Text.RemoveHtmlTags();
                post.Text = post.Text.Substring(0, Math.Min(post.Text.Length, 500));
            }

            var model = new BlogListingViewModel
            {
                Posts = posts,
                Categories = categories,
                Navigation = new NavigationViewModel
                {
                    TotalCount = await this.blog.TotalCount(),
                    PerPage = PostsPerPage,
                    CurrentPage = page
                }
            };

            return View(model);
        }

        public async Task<IActionResult> Article(int id)
        {
            var model = await this.blog.GetById(id);

            return View(model);
        }

        [Authorize(Roles = Writer + "," + Admin)]
        public async Task<IActionResult> Add()
        {
            var categories = await GetCategoriesToListItems();

            return View(new CreatePostViewModel
            {
                Categories = categories
            });
        }

        [HttpPost]
        [Authorize(Roles = Writer + "," + Admin)]
        public async Task<IActionResult> Add(CreatePostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = userManager.GetUserId(User);

                var categoryExist = await this.blog.CategoryExist(model.CategoryId);
                if (!categoryExist)
                {
                    return BadRequest();
                }

                var postId = await this.blog.AddArticle(model.Title, model.Text, model.CategoryId, userId);

                return RedirectToAction(nameof(Article), new { id = postId });
            }

            model.Categories = await GetCategoriesToListItems();

            return View(model);
        }

        [Authorize(Roles = Writer + "," + Admin)]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Writer + "," + Admin)]
        public async Task<IActionResult> AddCategory(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.blog.AddCategory(model.Name);

            return RedirectToAction(nameof(Articles));
        }
        private async Task<IEnumerable<SelectListItem>> GetCategoriesToListItems()
        {
            var categories = await blog.Categories();

            var categoriesListItems = categories.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

            return categoriesListItems;
        }
    }
}

Autoshop.Web/Controllers/ReviewsController.cs
namespace Autoshop.Web.Controllers
{
    using Autoshop.Models;
    using Autoshop.Services;
    using Autoshop.Web.Models;
    using Autoshop.Web.Models.ReviewsViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    using static Autoshop.Common.Constants.CommonConstants;

    public class ReviewsController : Controller
    {
        private readonly IReviewsService reviews;
        private readonly UserManager<User> userManager;

        public ReviewsController(IReviewsService reviews, UserManager<User> userManager)
        {
            this.reviews = reviews;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var reviewsToShow = await this.reviews.All(ReviewsMinRatingToPublish, page, ReviewsPerPage);

            var model = new ReviewListingViewModel
            {
                Reviews = reviewsToShow,
                Navigation = new NavigationViewModel
                {
                    TotalCount = await this.reviews.TotalCount(ReviewsMinRatingToPublish),
                    PerPage = ReviewsPerPage,
                    CurrentPage = page
                }
            };

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var user = await this.userManager.GetUserAsync(User);

            var model = new ReviewCreateViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Rating = 5
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(ReviewCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = this.userManager.GetUserId(User);
                await this.reviews.Add(model.Rating, model.Text, userId);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
    }
}

Autoshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Paco's Garage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/css/slider.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" async="async" defer="defer" data-cfasync="false" src="https://mylivechat.com/chatinline.aspx?hccid=31644956"></script>
</head>
<body>
    <div class="header">
        <div class="header_top">
            <div class="wrap container">
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <div class="logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" alt="Logo" /></a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="social-icons">
                            <ul>
                                <li><a class="facebook" href="https://www.facebook.com/pavel.ilchev" target="_blank"> </a></li>
                                <li><a class="twitter" href="https://twitter.com/PacosGarage" target="_blank"></a></li>
                                <li><a class="googleplus" href="https://plus.google.com/u/2/102737260430634775032" target="_blank"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="dail">
                            <h4>Call Us Now</h4>
                            <p><img src="~/images/icons/mobile.png"><a href="tel:0886808571">0886 808 571</a></p>
                            <p><a href='javascript:void(0)' onclick='MyLiveChat_OpenDialog()'><img src="~/images/icons/chat.png">Live Chat</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-default header-bottom">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li is-active-route asp-controller="Home" asp-action="Index"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li is-active-route asp-controller="Appointments" asp-action="Index"><a asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                        <li is-active-route asp-controller="Reviews" asp-action="Index"><a asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                        <li is-active-route asp-controller="Blog" asp-action="Articles"><a asp-area="" asp-controller="Blog" asp-action="Articles">Blog</a></li>
                        @if (User.IsInRole(Admin))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Panel<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="Administration" asp-controller="Users" asp-action="Users">Users</a></li>
                                    <li><a asp-area="Administration" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                                    <li><a asp-area="Administration" asp-controller="Specials" asp-action="Index">Specials</a></li>
                                    <li><a asp-area="Administration" asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </div>

    @RenderSection("Slideshow", required: false)
    @RenderSection("HomeCoupons", required: false)
    @RenderSection("HomeReviews", required: false)

    <div class="container main-content">
        @RenderBody()

        @if (TempData.ContainsKey(TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[TempDataSuccessMessageKey]
            </div>
        }
        @if (TempData.ContainsKey(TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[TempDataErrorMessageKey]
            </div>
        }
    </div>
    @RenderSection("GoogleMap", required: false)

    <div class="footer">
        <div class="wrap">
            <div class="footer_grides container">
                <div class="section group row">
                    <div class="col-sm-3 span_1_of_4">
                        <h3>Latest Posts</h3>
                        <div id="posts">
                        </div>
                    </div>

                    <div class="col-sm-3 span_1_of_4">
                        <h3>Connect With Us</h3>
                        <div class="social_icons">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/pavel.ilchev" class="facebook" target="_blank">
                                        <span class="icon"> &nbsp;</span> <span class="inner"><strong>Facebook</strong></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/PacosGarage" class="twitter" target="_blank">
                                        <span class="icon"> &nbsp;</span> <span class="inner"><strong>Twitter</strong></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-sm-3 span_1_of_4">
                        <h3>Navigate</h3>
                        <ul>
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                            <li><a asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                            <li><a asp-area="" asp-controller="Blog" asp-action="Articles">Blog</a></li>
                        </ul>
                    </div>

                    <div class="col-sm-3 span_1_of_4">
                        <h3>Location</h3>
                        <ul>
                            <li>Evlogi Georgiev 4, Varna</li>
                            <li>Bulgaria</li>
                            <li><span>Telephone:</span> +359 886 808 571</li>
                            <li><span>E-mail:</span> webmail.paco.garage@gmail.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            <div class="copy_right">
                <div class="wrap">
                    <p>Powered by <b>Paco</b>&copy; &ndash; Paco's Garage</p>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/js/jquery.nivo.slider.js" async="async" defer="defer"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>